# Generated by Django 4.1.6 on 2023-02-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_counter_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='session_key',
            field=models.CharField(default='8aswqe8e4gzk047017sphpjf36kzt5oc', max_length=100),
        ),
    ]
