# Generated by Django 4.1.6 on 2023-02-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0006_counter_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='session_key',
            field=models.CharField(default='8aswqe8e4gzk047017sphpjf36kzt5oc', max_length=100, null=True),
        ),
    ]
