# Generated by Django 4.1.6 on 2023-02-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='ip_address',
            field=models.CharField(default='127.0.0.1', max_length=15),
        ),
    ]
