# Generated by Django 4.1.6 on 2023-02-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_counter_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
