# Generated by Django 4.1.6 on 2023-02-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_alter_counter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='browser',
            field=models.CharField(default='Chrome', max_length=10),
        ),
        migrations.AddField(
            model_name='counter',
            name='browserVersion',
            field=models.CharField(default='10', max_length=10),
        ),
        migrations.AddField(
            model_name='counter',
            name='os',
            field=models.CharField(default='Windows', max_length=10),
        ),
        migrations.AddField(
            model_name='counter',
            name='osVersion',
            field=models.CharField(default='10', max_length=10),
        ),
    ]
