# Generated by Django 4.1.6 on 2023-02-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_counter_browser_counter_browserversion_counter_os_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='device',
            field=models.CharField(default='PC', max_length=10),
        ),
    ]
